<?php

namespace AppBundle\Repository;

/**
 * AccompagnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccompagnementRepository extends \Doctrine\ORM\EntityRepository
{
}
