<?php

namespace AppBundle\Repository;

/**
 * BurgerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BurgerRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getNb() {
  
        return $this->createQueryBuilder('l')
  
                        ->select('COUNT(l)')
                        	
                        ->where('l.publish = :publish')
                        
                        ->setParameter('publish', 0)
  
                        ->getQuery()
  
                        ->getSingleScalarResult();
  
    }
    
}
