<?php

namespace AppBundle\Repository;

/**
 * BurgerSpecialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BurgerSpecialRepository extends \Doctrine\ORM\EntityRepository
{
}
