<?php

namespace AppBundle\Repository;

/**
 * CategorieBoissonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieBoissonRepository extends \Doctrine\ORM\EntityRepository
{
}
